// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: networkMessage.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_networkMessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_networkMessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_networkMessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_networkMessage_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_networkMessage_2eproto;
class ExampleMessage;
struct ExampleMessageDefaultTypeInternal;
extern ExampleMessageDefaultTypeInternal _ExampleMessage_default_instance_;
class NodeInfo;
struct NodeInfoDefaultTypeInternal;
extern NodeInfoDefaultTypeInternal _NodeInfo_default_instance_;
class NodeInfoReply;
struct NodeInfoReplyDefaultTypeInternal;
extern NodeInfoReplyDefaultTypeInternal _NodeInfoReply_default_instance_;
class ProtobufMessage;
struct ProtobufMessageDefaultTypeInternal;
extern ProtobufMessageDefaultTypeInternal _ProtobufMessage_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::ExampleMessage* Arena::CreateMaybeMessage<::ExampleMessage>(Arena*);
template<> ::NodeInfo* Arena::CreateMaybeMessage<::NodeInfo>(Arena*);
template<> ::NodeInfoReply* Arena::CreateMaybeMessage<::NodeInfoReply>(Arena*);
template<> ::ProtobufMessage* Arena::CreateMaybeMessage<::ProtobufMessage>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class ProtobufMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProtobufMessage) */ {
 public:
  inline ProtobufMessage() : ProtobufMessage(nullptr) {}
  ~ProtobufMessage() override;
  explicit PROTOBUF_CONSTEXPR ProtobufMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProtobufMessage(const ProtobufMessage& from);
  ProtobufMessage(ProtobufMessage&& from) noexcept
    : ProtobufMessage() {
    *this = ::std::move(from);
  }

  inline ProtobufMessage& operator=(const ProtobufMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProtobufMessage& operator=(ProtobufMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProtobufMessage& default_instance() {
    return *internal_default_instance();
  }
  enum CommandCase {
    kExampleMessage = 100,
    kNodeInfo = 1,
    kNodeInfoReply = 2,
    COMMAND_NOT_SET = 0,
  };

  static inline const ProtobufMessage* internal_default_instance() {
    return reinterpret_cast<const ProtobufMessage*>(
               &_ProtobufMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProtobufMessage& a, ProtobufMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ProtobufMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProtobufMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProtobufMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProtobufMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProtobufMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProtobufMessage& from) {
    ProtobufMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProtobufMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProtobufMessage";
  }
  protected:
  explicit ProtobufMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kExampleMessageFieldNumber = 100,
    kNodeInfoFieldNumber = 1,
    kNodeInfoReplyFieldNumber = 2,
  };
  // .ExampleMessage ExampleMessage = 100;
  bool has_examplemessage() const;
  private:
  bool _internal_has_examplemessage() const;
  public:
  void clear_examplemessage();
  const ::ExampleMessage& examplemessage() const;
  PROTOBUF_NODISCARD ::ExampleMessage* release_examplemessage();
  ::ExampleMessage* mutable_examplemessage();
  void set_allocated_examplemessage(::ExampleMessage* examplemessage);
  private:
  const ::ExampleMessage& _internal_examplemessage() const;
  ::ExampleMessage* _internal_mutable_examplemessage();
  public:
  void unsafe_arena_set_allocated_examplemessage(
      ::ExampleMessage* examplemessage);
  ::ExampleMessage* unsafe_arena_release_examplemessage();

  // .NodeInfo NodeInfo = 1;
  bool has_nodeinfo() const;
  private:
  bool _internal_has_nodeinfo() const;
  public:
  void clear_nodeinfo();
  const ::NodeInfo& nodeinfo() const;
  PROTOBUF_NODISCARD ::NodeInfo* release_nodeinfo();
  ::NodeInfo* mutable_nodeinfo();
  void set_allocated_nodeinfo(::NodeInfo* nodeinfo);
  private:
  const ::NodeInfo& _internal_nodeinfo() const;
  ::NodeInfo* _internal_mutable_nodeinfo();
  public:
  void unsafe_arena_set_allocated_nodeinfo(
      ::NodeInfo* nodeinfo);
  ::NodeInfo* unsafe_arena_release_nodeinfo();

  // .NodeInfoReply NodeInfoReply = 2;
  bool has_nodeinforeply() const;
  private:
  bool _internal_has_nodeinforeply() const;
  public:
  void clear_nodeinforeply();
  const ::NodeInfoReply& nodeinforeply() const;
  PROTOBUF_NODISCARD ::NodeInfoReply* release_nodeinforeply();
  ::NodeInfoReply* mutable_nodeinforeply();
  void set_allocated_nodeinforeply(::NodeInfoReply* nodeinforeply);
  private:
  const ::NodeInfoReply& _internal_nodeinforeply() const;
  ::NodeInfoReply* _internal_mutable_nodeinforeply();
  public:
  void unsafe_arena_set_allocated_nodeinforeply(
      ::NodeInfoReply* nodeinforeply);
  ::NodeInfoReply* unsafe_arena_release_nodeinforeply();

  void clear_command();
  CommandCase command_case() const;
  // @@protoc_insertion_point(class_scope:ProtobufMessage)
 private:
  class _Internal;
  void set_has_examplemessage();
  void set_has_nodeinfo();
  void set_has_nodeinforeply();

  inline bool has_command() const;
  inline void clear_has_command();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    union CommandUnion {
      constexpr CommandUnion() : _constinit_{} {}
        ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized _constinit_;
      ::ExampleMessage* examplemessage_;
      ::NodeInfo* nodeinfo_;
      ::NodeInfoReply* nodeinforeply_;
    } command_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    uint32_t _oneof_case_[1];

  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networkMessage_2eproto;
};
// -------------------------------------------------------------------

class NodeInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NodeInfo) */ {
 public:
  inline NodeInfo() : NodeInfo(nullptr) {}
  ~NodeInfo() override;
  explicit PROTOBUF_CONSTEXPR NodeInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NodeInfo(const NodeInfo& from);
  NodeInfo(NodeInfo&& from) noexcept
    : NodeInfo() {
    *this = ::std::move(from);
  }

  inline NodeInfo& operator=(const NodeInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeInfo& operator=(NodeInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeInfo* internal_default_instance() {
    return reinterpret_cast<const NodeInfo*>(
               &_NodeInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(NodeInfo& a, NodeInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NodeInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NodeInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NodeInfo& from) {
    NodeInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NodeInfo";
  }
  protected:
  explicit NodeInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 Id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:NodeInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networkMessage_2eproto;
};
// -------------------------------------------------------------------

class NodeInfoReply final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:NodeInfoReply) */ {
 public:
  inline NodeInfoReply() : NodeInfoReply(nullptr) {}
  ~NodeInfoReply() override;
  explicit PROTOBUF_CONSTEXPR NodeInfoReply(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  NodeInfoReply(const NodeInfoReply& from);
  NodeInfoReply(NodeInfoReply&& from) noexcept
    : NodeInfoReply() {
    *this = ::std::move(from);
  }

  inline NodeInfoReply& operator=(const NodeInfoReply& from) {
    CopyFrom(from);
    return *this;
  }
  inline NodeInfoReply& operator=(NodeInfoReply&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const NodeInfoReply& default_instance() {
    return *internal_default_instance();
  }
  static inline const NodeInfoReply* internal_default_instance() {
    return reinterpret_cast<const NodeInfoReply*>(
               &_NodeInfoReply_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(NodeInfoReply& a, NodeInfoReply& b) {
    a.Swap(&b);
  }
  inline void Swap(NodeInfoReply* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(NodeInfoReply* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  NodeInfoReply* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<NodeInfoReply>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const NodeInfoReply& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const NodeInfoReply& from) {
    NodeInfoReply::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(NodeInfoReply* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "NodeInfoReply";
  }
  protected:
  explicit NodeInfoReply(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
  };
  // int32 Id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:NodeInfoReply)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t id_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networkMessage_2eproto;
};
// -------------------------------------------------------------------

class ExampleMessage final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ExampleMessage) */ {
 public:
  inline ExampleMessage() : ExampleMessage(nullptr) {}
  ~ExampleMessage() override;
  explicit PROTOBUF_CONSTEXPR ExampleMessage(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ExampleMessage(const ExampleMessage& from);
  ExampleMessage(ExampleMessage&& from) noexcept
    : ExampleMessage() {
    *this = ::std::move(from);
  }

  inline ExampleMessage& operator=(const ExampleMessage& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExampleMessage& operator=(ExampleMessage&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExampleMessage& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExampleMessage* internal_default_instance() {
    return reinterpret_cast<const ExampleMessage*>(
               &_ExampleMessage_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(ExampleMessage& a, ExampleMessage& b) {
    a.Swap(&b);
  }
  inline void Swap(ExampleMessage* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExampleMessage* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExampleMessage* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ExampleMessage>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ExampleMessage& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ExampleMessage& from) {
    ExampleMessage::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ExampleMessage* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ExampleMessage";
  }
  protected:
  explicit ExampleMessage(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kMessageFieldNumber = 1,
  };
  // string message = 1;
  void clear_message();
  const std::string& message() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_message(ArgT0&& arg0, ArgT... args);
  std::string* mutable_message();
  PROTOBUF_NODISCARD std::string* release_message();
  void set_allocated_message(std::string* message);
  private:
  const std::string& _internal_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_message(const std::string& value);
  std::string* _internal_mutable_message();
  public:

  // @@protoc_insertion_point(class_scope:ExampleMessage)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr message_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_networkMessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProtobufMessage

// .ExampleMessage ExampleMessage = 100;
inline bool ProtobufMessage::_internal_has_examplemessage() const {
  return command_case() == kExampleMessage;
}
inline bool ProtobufMessage::has_examplemessage() const {
  return _internal_has_examplemessage();
}
inline void ProtobufMessage::set_has_examplemessage() {
  _impl_._oneof_case_[0] = kExampleMessage;
}
inline void ProtobufMessage::clear_examplemessage() {
  if (_internal_has_examplemessage()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_.examplemessage_;
    }
    clear_has_command();
  }
}
inline ::ExampleMessage* ProtobufMessage::release_examplemessage() {
  // @@protoc_insertion_point(field_release:ProtobufMessage.ExampleMessage)
  if (_internal_has_examplemessage()) {
    clear_has_command();
    ::ExampleMessage* temp = _impl_.command_.examplemessage_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_.examplemessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::ExampleMessage& ProtobufMessage::_internal_examplemessage() const {
  return _internal_has_examplemessage()
      ? *_impl_.command_.examplemessage_
      : reinterpret_cast< ::ExampleMessage&>(::_ExampleMessage_default_instance_);
}
inline const ::ExampleMessage& ProtobufMessage::examplemessage() const {
  // @@protoc_insertion_point(field_get:ProtobufMessage.ExampleMessage)
  return _internal_examplemessage();
}
inline ::ExampleMessage* ProtobufMessage::unsafe_arena_release_examplemessage() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ProtobufMessage.ExampleMessage)
  if (_internal_has_examplemessage()) {
    clear_has_command();
    ::ExampleMessage* temp = _impl_.command_.examplemessage_;
    _impl_.command_.examplemessage_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufMessage::unsafe_arena_set_allocated_examplemessage(::ExampleMessage* examplemessage) {
  clear_command();
  if (examplemessage) {
    set_has_examplemessage();
    _impl_.command_.examplemessage_ = examplemessage;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ProtobufMessage.ExampleMessage)
}
inline ::ExampleMessage* ProtobufMessage::_internal_mutable_examplemessage() {
  if (!_internal_has_examplemessage()) {
    clear_command();
    set_has_examplemessage();
    _impl_.command_.examplemessage_ = CreateMaybeMessage< ::ExampleMessage >(GetArenaForAllocation());
  }
  return _impl_.command_.examplemessage_;
}
inline ::ExampleMessage* ProtobufMessage::mutable_examplemessage() {
  ::ExampleMessage* _msg = _internal_mutable_examplemessage();
  // @@protoc_insertion_point(field_mutable:ProtobufMessage.ExampleMessage)
  return _msg;
}

// .NodeInfo NodeInfo = 1;
inline bool ProtobufMessage::_internal_has_nodeinfo() const {
  return command_case() == kNodeInfo;
}
inline bool ProtobufMessage::has_nodeinfo() const {
  return _internal_has_nodeinfo();
}
inline void ProtobufMessage::set_has_nodeinfo() {
  _impl_._oneof_case_[0] = kNodeInfo;
}
inline void ProtobufMessage::clear_nodeinfo() {
  if (_internal_has_nodeinfo()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_.nodeinfo_;
    }
    clear_has_command();
  }
}
inline ::NodeInfo* ProtobufMessage::release_nodeinfo() {
  // @@protoc_insertion_point(field_release:ProtobufMessage.NodeInfo)
  if (_internal_has_nodeinfo()) {
    clear_has_command();
    ::NodeInfo* temp = _impl_.command_.nodeinfo_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_.nodeinfo_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NodeInfo& ProtobufMessage::_internal_nodeinfo() const {
  return _internal_has_nodeinfo()
      ? *_impl_.command_.nodeinfo_
      : reinterpret_cast< ::NodeInfo&>(::_NodeInfo_default_instance_);
}
inline const ::NodeInfo& ProtobufMessage::nodeinfo() const {
  // @@protoc_insertion_point(field_get:ProtobufMessage.NodeInfo)
  return _internal_nodeinfo();
}
inline ::NodeInfo* ProtobufMessage::unsafe_arena_release_nodeinfo() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ProtobufMessage.NodeInfo)
  if (_internal_has_nodeinfo()) {
    clear_has_command();
    ::NodeInfo* temp = _impl_.command_.nodeinfo_;
    _impl_.command_.nodeinfo_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufMessage::unsafe_arena_set_allocated_nodeinfo(::NodeInfo* nodeinfo) {
  clear_command();
  if (nodeinfo) {
    set_has_nodeinfo();
    _impl_.command_.nodeinfo_ = nodeinfo;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ProtobufMessage.NodeInfo)
}
inline ::NodeInfo* ProtobufMessage::_internal_mutable_nodeinfo() {
  if (!_internal_has_nodeinfo()) {
    clear_command();
    set_has_nodeinfo();
    _impl_.command_.nodeinfo_ = CreateMaybeMessage< ::NodeInfo >(GetArenaForAllocation());
  }
  return _impl_.command_.nodeinfo_;
}
inline ::NodeInfo* ProtobufMessage::mutable_nodeinfo() {
  ::NodeInfo* _msg = _internal_mutable_nodeinfo();
  // @@protoc_insertion_point(field_mutable:ProtobufMessage.NodeInfo)
  return _msg;
}

// .NodeInfoReply NodeInfoReply = 2;
inline bool ProtobufMessage::_internal_has_nodeinforeply() const {
  return command_case() == kNodeInfoReply;
}
inline bool ProtobufMessage::has_nodeinforeply() const {
  return _internal_has_nodeinforeply();
}
inline void ProtobufMessage::set_has_nodeinforeply() {
  _impl_._oneof_case_[0] = kNodeInfoReply;
}
inline void ProtobufMessage::clear_nodeinforeply() {
  if (_internal_has_nodeinforeply()) {
    if (GetArenaForAllocation() == nullptr) {
      delete _impl_.command_.nodeinforeply_;
    }
    clear_has_command();
  }
}
inline ::NodeInfoReply* ProtobufMessage::release_nodeinforeply() {
  // @@protoc_insertion_point(field_release:ProtobufMessage.NodeInfoReply)
  if (_internal_has_nodeinforeply()) {
    clear_has_command();
    ::NodeInfoReply* temp = _impl_.command_.nodeinforeply_;
    if (GetArenaForAllocation() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    _impl_.command_.nodeinforeply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::NodeInfoReply& ProtobufMessage::_internal_nodeinforeply() const {
  return _internal_has_nodeinforeply()
      ? *_impl_.command_.nodeinforeply_
      : reinterpret_cast< ::NodeInfoReply&>(::_NodeInfoReply_default_instance_);
}
inline const ::NodeInfoReply& ProtobufMessage::nodeinforeply() const {
  // @@protoc_insertion_point(field_get:ProtobufMessage.NodeInfoReply)
  return _internal_nodeinforeply();
}
inline ::NodeInfoReply* ProtobufMessage::unsafe_arena_release_nodeinforeply() {
  // @@protoc_insertion_point(field_unsafe_arena_release:ProtobufMessage.NodeInfoReply)
  if (_internal_has_nodeinforeply()) {
    clear_has_command();
    ::NodeInfoReply* temp = _impl_.command_.nodeinforeply_;
    _impl_.command_.nodeinforeply_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void ProtobufMessage::unsafe_arena_set_allocated_nodeinforeply(::NodeInfoReply* nodeinforeply) {
  clear_command();
  if (nodeinforeply) {
    set_has_nodeinforeply();
    _impl_.command_.nodeinforeply_ = nodeinforeply;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:ProtobufMessage.NodeInfoReply)
}
inline ::NodeInfoReply* ProtobufMessage::_internal_mutable_nodeinforeply() {
  if (!_internal_has_nodeinforeply()) {
    clear_command();
    set_has_nodeinforeply();
    _impl_.command_.nodeinforeply_ = CreateMaybeMessage< ::NodeInfoReply >(GetArenaForAllocation());
  }
  return _impl_.command_.nodeinforeply_;
}
inline ::NodeInfoReply* ProtobufMessage::mutable_nodeinforeply() {
  ::NodeInfoReply* _msg = _internal_mutable_nodeinforeply();
  // @@protoc_insertion_point(field_mutable:ProtobufMessage.NodeInfoReply)
  return _msg;
}

inline bool ProtobufMessage::has_command() const {
  return command_case() != COMMAND_NOT_SET;
}
inline void ProtobufMessage::clear_has_command() {
  _impl_._oneof_case_[0] = COMMAND_NOT_SET;
}
inline ProtobufMessage::CommandCase ProtobufMessage::command_case() const {
  return ProtobufMessage::CommandCase(_impl_._oneof_case_[0]);
}
// -------------------------------------------------------------------

// NodeInfo

// int32 Id = 1;
inline void NodeInfo::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t NodeInfo::_internal_id() const {
  return _impl_.id_;
}
inline int32_t NodeInfo::id() const {
  // @@protoc_insertion_point(field_get:NodeInfo.Id)
  return _internal_id();
}
inline void NodeInfo::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void NodeInfo::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:NodeInfo.Id)
}

// -------------------------------------------------------------------

// NodeInfoReply

// int32 Id = 1;
inline void NodeInfoReply::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t NodeInfoReply::_internal_id() const {
  return _impl_.id_;
}
inline int32_t NodeInfoReply::id() const {
  // @@protoc_insertion_point(field_get:NodeInfoReply.Id)
  return _internal_id();
}
inline void NodeInfoReply::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void NodeInfoReply::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:NodeInfoReply.Id)
}

// -------------------------------------------------------------------

// ExampleMessage

// string message = 1;
inline void ExampleMessage::clear_message() {
  _impl_.message_.ClearToEmpty();
}
inline const std::string& ExampleMessage::message() const {
  // @@protoc_insertion_point(field_get:ExampleMessage.message)
  return _internal_message();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ExampleMessage::set_message(ArgT0&& arg0, ArgT... args) {
 
 _impl_.message_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ExampleMessage.message)
}
inline std::string* ExampleMessage::mutable_message() {
  std::string* _s = _internal_mutable_message();
  // @@protoc_insertion_point(field_mutable:ExampleMessage.message)
  return _s;
}
inline const std::string& ExampleMessage::_internal_message() const {
  return _impl_.message_.Get();
}
inline void ExampleMessage::_internal_set_message(const std::string& value) {
  
  _impl_.message_.Set(value, GetArenaForAllocation());
}
inline std::string* ExampleMessage::_internal_mutable_message() {
  
  return _impl_.message_.Mutable(GetArenaForAllocation());
}
inline std::string* ExampleMessage::release_message() {
  // @@protoc_insertion_point(field_release:ExampleMessage.message)
  return _impl_.message_.Release();
}
inline void ExampleMessage::set_allocated_message(std::string* message) {
  if (message != nullptr) {
    
  } else {
    
  }
  _impl_.message_.SetAllocated(message, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.message_.IsDefault()) {
    _impl_.message_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ExampleMessage.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_networkMessage_2eproto
